### ISSUE TITLE
Null Allele and Missing Data

### ISSUE THREAD

**Issue by Denlior** [arjun-1/BEASTvntr#3]
Either I am missing something, or there is no way to use datasets with some repeat length measurements omitted.

**Comment by arjun-1** [comment]
You can specify a repeat length of `-1`, which BEAST2 internally will treat as a missing repeat length. Normally, you can use the `?` character in BEAST2 to represent any omitted data, but that currently doesn't work in the add-on. It's true that this is unexpected behavior, so I will implement a fix for this issue in the future.
